### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by axello**
Thanks for this great educational resource. STEM teachers rejoice.

I have adapted also the 'HAT' reference to 'PET', which is also something you wear AND has three letters: handy!

I hope the text fits, as English is a very compact language, Dutch and German less so.

Any questions, feel free to comment here or on twitter: @axello

### CODE REVIEW

**Comment by cimm** [comment]
Hey @tanyafish, just finished decoding both Morse messages with my kids. They loved it! What a great discussion starter, we learned so many new thing together from a simple parachute. Thank you!

I wanted to translate it to Dutch but noticed @axello already beat me to it. Anyways, @axello, laat me weten als ik ergens mee kan helpen!

**Review by tanyafish — APPROVED** [review]
Wonderful - thanks for the time and effort you put in to this! I will make a printable pdf in Dutch using your translation, with credit to you, and then link it from the Dutch part of the README.md file.

**Comment by tanyafish** [comment]
> Hey @tanyafish, just finished decoding both Morse messages with my 2 kids. They loved it! What a great discussion starter, we learned so many new thing together from a simple parachute. Thank you!
> 
> I wanted to translate it to Dutch but noticed @axello already beat me to it. Anyways, @axello, laat me weten als ik ergens mee kan helpen!

Cimm, it would be lovely to have a second pair of eyes on the translation as a proofreader! My Dutch is at the level where I can order pancakes and express appreciation for the pancakes, which is not very useful here!

**Comment by cimm** [comment]
Good idea @tanyafish. Attached the corrected version, small tweaks, nothing mayor. Mainly some English "the" leftovers. 

[Het_Parachute_Bericht_NL.pdf](https://github.com/tanyafish/parachute/files/6054837/Het_Parachute_Bericht_NL.pdf)

**Comment by axello** [comment]
Wow!
Good finds Simon!
My mind blurs English and Dutch too much, so De and The take up a similar slot in my brain.

Thanks for the proofread!

**Pull request merged**
