### PR TITLE
feat: spanish translation

### PR DESCRIPTION
**Pull request by robotmischief**
Hi! Just did a Spanish translation so I can use it with my students. This is a nice initiative you did. Thanks.

### CODE REVIEW

**Review by tanyafish — CHANGES_REQUESTED** [review]
Thanks for the translation of the readme file. Unfortunately if I accept these changes as they are, it would delete the English version - can you add your text to the bottom of the file instead of deleting the English lines.

The other file, the translation of the cards, is fine as it is.

Again, thanks for the translation! This conversation is recorded in github so you can track your contributions.

**Comment by robotmischief** [comment]
oops, my bad sorry. I'll do the same for the teacher's guide. Thanks

**Review by tanyafish — APPROVED** [review]
Looks good! Thanks

**Comment by tanyafish** [comment]
> oops, my bad sorry. I'll do the same for the teacher's guide. Thanks

If you could do the teachers guide as a separate file - teachersguideESP.md - that would be preferable.

**Pull request merged**
